name: property_051
description: A Real Estate Solution.

version: 1.0.01+36

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter_svg: ^1.1.6
  dio: ^4.0.6
  intl: ^0.18.0
  cached_network_image: ^3.2.1
  animations: ^2.0.3
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.0.9
  flutter_easyloading: ^3.0.5
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  get_storage: ^2.0.3
  infinite_scroll_pagination: ^3.2.0
  dartz: ^0.10.1
  flutter_spinkit: ^5.1.0
  flutter_image_slideshow: ^0.1.4
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^0.8.5+3
  phone_number: ^1.0.0
  shimmer: ^2.0.0

  #Location
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  google_maps_flutter: ^2.1.12

  #Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.2
  firebase_messaging: ^14.2.1

  #Social Login
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^5.0.7
  sign_in_with_apple: ^4.1.0

  #Third Party
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app/newLogo.jpg"

flutter:
  uses-material-design: true
  assets:
    - images/app/
    - images/gif/
    - images/icons/
    - images/converter/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/roboto/Roboto-Light.ttf
          weight: 200
        - asset: fonts/roboto/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/roboto/Roboto-Italic.ttf
          style: italic
    - family: Mulish
      fonts:
        - asset: fonts/mulish/Mulish-Black.ttf
          weight: 900
        - asset: fonts/mulish/Mulish-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/mulish/Mulish-Bold.ttf
          weight: 600
        - asset: fonts/mulish/Mulish-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/mulish/Mulish-ExtraBold.ttf
          weight: 800
        - asset: fonts/mulish/Mulish-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/mulish/Mulish-ExtraLight.ttf
          weight: 200
        - asset: fonts/mulish/Mulish-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/mulish/Mulish-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/mulish/Mulish-Light.ttf
          weight: 200
        - asset: fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: fonts/mulish/Mulish-SemiBold.ttf
          weight: 500
